DROP TABLE people PURGE;
DROP SEQUENCE people_person_id_seq;
DROP TABLE categories PURGE;
DROP SEQUENCE categories_category_id_seq;
DROP TABLE certifications PURGE;
DROP TABLE certification_levels PURGE;
DROP TABLE events_artists PURGE;
DROP TABLE event_details PURGE;
DROP TABLE registrations PURGE;
DROP TABLE events PURGE;
DROP SEQUENCE events_event_id_seq;
DROP TABLE event_slots PURGE;
DROP SEQUENCE event_slots_id_seq;
DROP TABLE invalid_tables PURGE;
DROP TABLE top_albums PURGE;
DROP SEQUENCE top_albums_top_album_id_seq;
DROP TABLE year_favorite_albums PURGE;
DROP TABLE favorite_albums PURGE;
DROP TABLE record_deals PURGE;
DROP TABLE record_labels PURGE;
DROP TABLE other_user_details PURGE;
DROP TABLE user_details PURGE;