DROP TABLE blobs PURGE;
DROP TABLE owns_on_tape PURGE;
DROP TABLE owns_on_cd PURGE;
DROP TABLE songs PURGE;
DROP SEQUENCE songs_song_id_seq;
DROP TABLE albums PURGE;
DROP SEQUENCE albums_album_id_seq;
DROP TABLE artists PURGE;
DROP SEQUENCE artists_artist_id_seq;
DROP TABLE users_groups PURGE;
DROP SEQUENCE groups_group_id_seq;
DROP TABLE groups PURGE;
DROP SEQUENCE users_user_id_seq;
DROP TABLE users PURGE;