BEGIN;
DELETE FROM people;
DELETE FROM categories;
DELETE FROM certifications;
DELETE FROM certification_levels;
DELETE FROM events_artists;
DELETE FROM event_details;
DELETE FROM registrations;
DELETE FROM event_slots;
DELETE FROM events;
DELETE FROM invalid_tables;
DELETE FROM top_albums;
DELETE FROM year_favorite_albums;
DELETE FROM favorite_albums;
DELETE FROM record_deals;
DELETE FROM record_labels;
DELETE FROM other_user_details;
DELETE FROM user_details;
COMMIT;
ALTER TABLE people ALTER COLUMN person_id RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN category_id RESTART WITH 1;
ALTER TABLE event_slots ALTER COLUMN id RESTART WITH 1;
ALTER TABLE events ALTER COLUMN event_id RESTART WITH 1;
ALTER TABLE top_albums ALTER COLUMN top_album_id RESTART WITH 1;