BEGIN;
DELETE FROM people;
DELETE FROM categories;
DELETE FROM certifications;
DELETE FROM certification_levels;
DELETE FROM events_artists;
DELETE FROM event_details;
DELETE FROM registrations;
DELETE FROM event_slots;
DELETE FROM events;
DELETE FROM invalid_tables;
DELETE FROM top_albums;
DELETE FROM year_favorite_albums;
DELETE FROM favorite_albums;
DELETE FROM record_deals;
DELETE FROM record_labels;
DELETE FROM other_user_details;
DELETE FROM user_details;
COMMIT;
DELETE FROM sqlite_sequence WHERE name = 'people';
DELETE FROM sqlite_sequence WHERE name = 'categories';
DELETE FROM sqlite_sequence WHERE name = 'event_slots';
DELETE FROM sqlite_sequence WHERE name = 'events';
DELETE FROM sqlite_sequence WHERE name = 'top_albums';